eclipseWorkspace/AK SFDC/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Relationship__c</fullName>
        <label>Account Relationship</label>
        <picklist>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Responded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Idle Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Extinct</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

eclipseWorkspace/AK SFDC/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Relationship__c</fullName>
        <formula>IF(Account.RecordType.Id = &quot;012b0000000Tyc8&quot;,
Account.Parent_Account_Relationship__c,
TEXT(Account.Account_Relationship__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Relationship</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FunnelStageInt__c</fullName>
        <formula>CASE(
Funnel_Stage__c,
&quot;Lead&quot;, 1,
&quot;Responded&quot;, 2,
&quot;Qualified&quot;, 3,
&quot;Customer&quot;, 4,
0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FunnelStageInt</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Funnel_Stage__c</fullName>
        <label>Funnel Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Responded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>For Contacts with whom we are or have worked or Prospects who we are or have approached.</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

eclipseWorkspace/AK SFDC/src/classes/akUpdateAccountTest.cls
@isTest 
private class akUpdateAccountTest {
    static testMethod void akUpdateAccountRelTest() {
		// Setup and Insert Test Account
		Account testAcct = new Account(Name='Test Account', Account_Relationship__c='', BillingCity='Test', BillingCountryCode='GB');
	    insert testAcct;
        ID testAcctID = testAcct.Id;

        // Setup and Insert Test Contact
        Contact testContact = new Contact(LastName='TestContact', FirstName='TestContactF', Funnel_Stage__c='', MailingCountryCode='GB', AccountId=TestAcctID);
        insert testContact;
        ID testContactID = testContact.Id;
        
        // Test the Account Relationship is Blank
		testAcct = [SELECT Id, Account_Relationship__c FROM Account WHERE Id = :testAcctID];
        System.assertEquals(null, testAcct.Account_Relationship__c);

        // Retrieve the Test Contact and update Funnel Stage Field on Test Contact
        testContact = [SELECT Id, Funnel_Stage__c FROM Contact WHERE Id = :testContactID];
        testContact.Funnel_Stage__c = 'To Contact';
        update testContact;
        
        // Test the Account Relationship is Blank
		testAcct = [SELECT Id, Account_Relationship__c FROM Account WHERE Id = :testAcctID];
        System.assertEquals(null, testAcct.Account_Relationship__c);
        
        // Retrieve the Test Contact and update Funnel Stage Field on Test Contact
        testContact = [SELECT Id, Funnel_Stage__c FROM Contact WHERE Id = :testContactID];
        testContact.Funnel_Stage__c = 'Contacted';
        update testContact;
		        
        // Test the Account Relationship has changed to Contacted
		testAcct = [SELECT Id, Account_Relationship__c FROM Account WHERE Id = :testAcctID];
        System.assertEquals('Contacted', testAcct.Account_Relationship__c);

        
        // Retrieve the Test Contact and update Funnel Stage Field on Test Contact
        testContact = [SELECT Id, Funnel_Stage__c FROM Contact WHERE Id = :testContactID];
        testContact.Funnel_Stage__c = 'Responded';
        update testContact;
		        
        // Test the Account Relationship has changed to Responded
		testAcct = [SELECT Id, Account_Relationship__c FROM Account WHERE Id = :testAcctID];
        System.assertEquals('Responded', testAcct.Account_Relationship__c);

        // Retrieve the Test Contact and update Funnel Stage Field on Test Contact
        testContact = [SELECT Id, Funnel_Stage__c FROM Contact WHERE Id = :testContactID];
        testContact.Funnel_Stage__c = 'Qualified';
        update testContact;
        
        // Test the Account Relationship has changed to Qualified Lead
		testAcct = [SELECT Id, Account_Relationship__c FROM Account WHERE Id = :testAcctID];
        System.assertEquals('Qualified Lead', testAcct.Account_Relationship__c);

		// Retrieve the Test Contact and update Funnel Stage Field on Test Contact
        testContact = [SELECT Id, Funnel_Stage__c FROM Contact WHERE Id = :testContactID];
        testContact.Funnel_Stage__c = 'Customer';
        update testContact;
        
        // Test the Account Relationship has changed to Active Account
		testAcct = [SELECT Id, Account_Relationship__c FROM Account WHERE Id = :testAcctID];
        System.assertEquals('Active Account', testAcct.Account_Relationship__c);
        
		// Retrieve the Test Contact and update Funnel Stage Field on Test Contact
        testContact = [SELECT Id, Funnel_Stage__c, FunnelStageInt__c FROM Contact WHERE Id = :testContactID];
        testContact.Funnel_Stage__c = 'Contacted';
        update testContact;
        
        // Test the Account Relationship has not changed
		testAcct = [SELECT Id, Account_Relationship__c FROM Account WHERE Id = :testAcctID];
        System.assertEquals('Active Account', testAcct.Account_Relationship__c);

    }
}