eclipseWorkspace/AK SFDC/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccRelationshipInt__c</fullName>
        <formula>CASE( 
Account_Relationship__c, 
&quot;Lead&quot;, 1, 
&quot;Responded&quot;, 2, 
&quot;Qualified Lead&quot;, 3, 
&quot;Active Prospect&quot;, 3,
&quot;Active Account&quot;, 4,
&quot;Idle Account&quot;, 4,
&quot;Extinct&quot;, 5,
0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AccRelationshipInt</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Account_Relationship__c</fullName>
        <label>Account Relationship</label>
        <picklist>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Responded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Idle Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Extinct</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

eclipseWorkspace/AK SFDC/src/classes/akUpdateAccount.cls
public class akUpdateAccount {
    public void UpdateAccountRel(String updAccountId, Decimal newFunnelStage){
        Account updAccount = [SELECT Id, Name, Account_Relationship__c, AccRelationshipInt__c FROM Account WHERE Id = :updAccountId];

        Decimal updAccountStage = updAccount.AccRelationshipInt__c;
        String oldRel = updAccount.Account_Relationship__c;
        String newRel;
        
        if (newFunnelStage > updAccountStage){
        	if (newFunnelStage == 1){
        		newRel = 'Contacted';
        	}
        	else if (newFunnelStage == 2){
        		newRel = 'Responded';
        	}
        	else if (newFunnelStage == 3){
        		newRel = 'Qualified Lead';
        	}
        	else if (newFunnelStage == 4){
        		newRel = 'Active Account';
        	}
        	else {
        		newRel = oldRel;
        	}
			updAccount.Account_Relationship__c = newRel;
            update updAccount;
//          System.debug('I updated ' + updAccount.Name + ' with ID ' + updAccountId + ' to ' + newRel);            
        }
        
        else{
//	        System.debug('Account Relationship was not Improved, hence no change.');            
        }
    }
}