eclipseWorkspace/AK SFDC/src/objects/ISO_alpha3_Country_Code__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Akascia_Territory__c</fullName>
        <label>Akascia Territory</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>ISO alpha3 Country Code</label>
</CustomObject>

eclipseWorkspace/AK SFDC/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Akascia_Territory__c</fullName>
        <label>Akascia Territory</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CB_Country_Code__c</fullName>
        <label>CB: Country Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CB_Founded_Year__c</fullName>
        <label>CB: Founded Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CB_Funding_Total_USD__c</fullName>
        <label>CB: Funding Total USD</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Check_Age__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Check Age</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Check_Funding__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Check Funding</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>48</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

eclipseWorkspace/AK SFDC/src/classes/AKTestLeadClass.cls
@isTest 
private class AKTestLeadClass {
    static testMethod void AK_updLeadFromCB() {
       ISO_alpha3_Country_Code__c cCode = new ISO_alpha3_Country_Code__c(Name='USA', Region__c='Americas', Akascia_Territory__c='Americas');
       Lead ld = new Lead(LastName='CEO', Company='TestCompany', CB_Country_Code__c='USA', CB_Founded_Year__c='2005', CB_Funding_Total_USD__c=2000000);

       // Insert lead and ISO Country Custom Setting
       insert cCode;
       insert ld;
    
       // Retrieve the new lead
       ld = [SELECT Check_Age__c, Check_Funding__c, Region__c, Akascia_Territory__c, Status FROM Lead WHERE Id =:ld.Id];

       // Test that the trigger correctly updated the lead
       System.assertEquals(true, ld.Check_Age__c);
       System.assertEquals(false, ld.Check_Funding__c);
       System.assertEquals('Americas', ld.Region__c);
       System.assertEquals('Americas', ld.Akascia_Territory__c);
       
    }
}